### PR TITLE
Replace the URL to DNAstack's decommissioned or soon-to-be-decommissioned data connect services

### PR DESCRIPTION
**Pull request by shiroyuki**
This PR is to replace the URL to DNAstack's decommissioned or soon-to-be-decommissioned data connect services.

| Old endpoint | Reason |
| --- | --- |
| `https://data-connect-trino-public.prod.dnastack.com/` | Soon to be decommissioned |
| `https://ga4gh-search-adapter-presto-public.prod.dnastack.com/` | Soon to be decommissioned |

The new endpoint is `https://data.publisher.dnastack.com/data-connect/`.

> NOTE: The tables have been replaced with the same/equivalent one.

### CODE REVIEW

**Comment by ianfore** [comment]
https://data.publisher.dnastack.com/data-connect/tables

gives the following error:
```
{
    "errors": [
        {
            "status": 401,
            "title": "Access Denied: HTTP 401: User does not have permission to access the table [system.metadata.catalogs]. [traceID: ffe755be6f7e249f | spanID: 52db90931f6929c2]",
            "details": "ffe755be6f7e249f: USER_ERROR: 4: PERMISSION_DENIED"
        }
    ],
    "error": {
        "status": 401,
        "title": "Access Denied: HTTP 401: User does not have permission to access the table [system.metadata.catalogs]. [traceID: ffe755be6f7e249f | spanID: 52db90931f6929c2]",
        "details": "ffe755be6f7e249f: USER_ERROR: 4: PERMISSION_DENIED"
    }
}
```

**Comment by mbarkley** [comment]
@ianfore we think we've addressed the issue you reported when you last tried this. We'd love if you could try it out again, but if you don't have time, we'd still like to merge this change on Friday as the old table names will become unusable soon.

**Comment by ianfore** [comment]
@mbarkley . All I've had time to do at the moment is check the error I was getting before doesn't occur with the corrected endpoint.
https://publisher-data.prod.dnastack.com/data-connect

There are many table name changes also, and haven't has a chance to look at all of those.
Same answer for the following PR on the tutorial repo (which is probably the more important one)
https://github.com/ga4gh/Get-Started-with-GA4GH-APIs/pull/43

**Comment by ianfore** [comment]
@mbarkley 
I also hadn't checked whether the schema for the tables had been migrated correctly.

For notebook 2-3a the original table was 
thousand_genomes.onek_genomes.sra_drs_files
See the schema that was previous provided in response to /tables/thousand_genomes.onek_genomes.sra_drs_files/info at [this commit](https://github.com/ga4gh/Get-Started-with-GA4GH-APIs/blob/de6713ac040ff58f262abcead04df44fe08925a5/presenter/completed/2-3a%20Finding%20files-completed.ipynb)

The replacement table on the new server seems to be:
collections.public_datasets.onek_genomes_sra_drs_files
The schema provided in response to is an autogenerated schema

The old server was making use of static json schema files that had been provided for specific datasets . These don't seem to have migrated to the new server. Or perhaps just not to the location on the new server where they would be expected to be found.

**Comment by shiroyuki** [comment]
I am in the process of restoring the custom schema. As it involves fixing a bug on our backend service, it should be ready by the end of next week.

**Pull request merged**
